# GoReleaser configuration for artifact-cli
# https://goreleaser.com/

# Project name and version
project_name: artifact-cli

# Build configuration
builds:
  - id: artifact-cli
    binary: artifact-cli
    main: ./cmd/root.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# Archive configuration
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*
      - docs/*
    format: tar.gz

# Checksums
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# GitHub release configuration
release:
  github:
    owner: jorgemoralespou
    name: educates-artifact-cli
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Changelog
    
    See the [CHANGELOG.md](CHANGELOG.md) file for details.
  footer: |
    ## Installation
    
    ### Using GoReleaser (recommended)
    
    Download the latest release from the [releases page](https://github.com/jorgemoralespou/educates-artifact-cli/releases).
    

# Changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - '^chore:'

# Milestone configuration
milestones:
  - repo: jorgemoralespou/educates-artifact-cli
    close: true

# Before hooks
before:
  hooks:
    - go mod tidy
    - go mod verify
    - go vet ./...
    - go test ./...

# After hooks
after:
  hooks:
    - echo "Release {{ .Version }} completed successfully!"

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

# Announcements
announce:
  skip: "{{gt .Patch 0}}"
  twitter:
    enabled: false
  reddit:
    enabled: false
  linkedin:
    enabled: false
  mastodon:
    enabled: false
  slack:
    enabled: false
  discord:
    enabled: false
  teams:
    enabled: false
  smtp:
    enabled: false
  telegram:
    enabled: false
  mattermost:
    enabled: false
  rocketchat:
    enabled: false
  matrix:
    enabled: false
  googlechat:
    enabled: false
  webhook:
    enabled: false

# Blobs (for additional files)
blobs:
  - provider: github
    ids:
      - artifact-cli
    folder: "{{ .ProjectName }}_{{ .Version }}"
    globs:
      - "*.tar.gz"
      - "*.zip"
      - "*.deb"
      - "*.rpm"
      - "*.snap"

# Universal binaries (for Apple Silicon)
universal_binaries:
  - replace: true
    goos:
      - darwin

# Source configuration
source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_src"
  format: tar.gz
  files:
    - "*.go"
    - "go.mod"
    - "go.sum"
    - "README.md"
    - "LICENSE*"
    - "CHANGELOG*"
    - "docs/**/*"
    - "specs/**/*"
    - "Taskfile.yml"
    - ".goreleaser.yml"
