name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache: true

    - name: Install Task
      uses: go-task/setup-task@v1

    - name: Build
      run: task build-all      

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: artifact-cli-${{ matrix.os }}-${{ matrix.arch }}
        path: bin/artifact-cli**
        retention-days: 7 